### PR TITLE
[API Breaking Change] Optimized rendering

### LINKED ISSUE #3: Crash on Linux
Hello,
Gifs work fine for me on Windows.
However on linux they appear to randomly crash the application.

```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   at Avalonia.Rendering.DirtyVisuals.Add(IVisual visual)
   at AvaloniaGif.GifInstance.RenderTick(TimeSpan time)
   at Avalonia.Rendering.DefaultRenderTimer.InternalTick(TimeSpan tickCount)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

```

This happened even when there were no visible Gifs on screen

### PR DESCRIPTION
**Pull request by jmacato**
Should fix the InvalidOperationExceptions that some are getting.

Fixes https://github.com/jmacato/AvaloniaGif/issues/3 

Please comment if you have any objections on this API change.

### CODE REVIEW

File: AvaloniaGif/GifImage.cs [hunk 1]
```diff
@@ -3,132 +3,181 @@
...
+            set => SetValue(StretchDirectionProperty, value);
         }
 
-        public static void SetAutoStart(Image target, bool value)
+        public Stretch Stretch
         {
-            target.SetValue(AutoStartProperty, value);
+            get => GetValue(StretchProperty);
+            set => SetValue(StretchProperty, value);
         }
```
Comment (jmacato) [inline AvaloniaGif/GifImage.cs:79]:
```suggestion
```

File: AvaloniaGif/GifImage.cs [hunk 2]
```diff
@@ -3,132 +3,180 @@
...
+using Avalonia.Media;
+using Avalonia.Media.Imaging;
+using Avalonia.Threading;
+using Avalonia.Media;
+using Avalonia.Media.Imaging;
 
 namespace AvaloniaGif
 {
-    public class GifImage
+
```
Comment (jmacato) [inline AvaloniaGif/GifImage.cs]:
```suggestion
```
